

[build]
  command = "cd Frontend && npm install && npm run build"
  publish = "Frontend/dist"

[dev]
  command = "cd Frontend && npm install && npm run dev"
  targetPort = 3000
  port = 8888
  framework = "#custom"

[build.environment]
  MONGODB_URI = "mongodb+srv://aashishsingh24032005:AshishMaurya123@cluster0.a2uldlq.mongodb.net"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/:splat"
  status = 200
  force = true







