[build]
  command = "npm run build"
  publish = "frontend/dist"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  framework = "#custom"

[build.environment]
  MONGODB_URI = "mongodb+srv://aashishsingh24032005:AshishMaurya123@cluster0.a2uldlq.mongodb.net"
